from setuptools import setup, find_packages

setup(
    name='galois-field',
    version='0.2.0',
    packages=find_packages(),
    install_requires=[],
    description='A comprehensive library for Galois Field (GF(2^m)) operations with extended algebraic functions',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Lvc4 @GitHub',
    license='MIT',
    url='https://github.com/Lvc4/galois-field',
    python_requires='>=3.6',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research', 
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Scientific/Engineering :: Mathematics',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    keywords='galois field finite field algebra cryptography mathematics',
)